name: Release - Model Service

# To configure the release based on git actions (aka mention release number)
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK (for Maven) for pom.xml file read
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Parse the version from pom.xml file and validate it
        run: |
          #1. Read version pom.xml using MVN
          
          IMG_POM_VERSION=$(mvn -q -Dexec.cleanupDaemonThreads=false help:evaluate -D expression=project.version -D forceStdout)
          echo "Version found in pom.xml: $IMG_POM_VERSION"

          #2. Extract information from tag by stripping first 11 chars
          
          TAG_VERSION=${GITHUB_REF:11}
          echo "Version from tag: $TAG_VERSION"

          #3. Validate the similarity btw tag version from pom.xml and github
          
          if [ "$IMG_POM_VERSION" != "$TAG_VERSION" ]; then
            echo "ERROR: pom.xml version ($IMG_POM_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          
          NEW_VERSION="$IMG_POM_VERSION"
          
          MAJOR=$(echo "$NEW_VERSION" | cut -d . -f 1)
          MINOR=$(echo "$NEW_VERSION" | cut -d . -f 2)
          PATCH=$(echo "$NEW_VERSION" | cut -d . -f 3)
          
          echo "version=$NEW_VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Build and push to registry
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          IMG=${IMG@L}
          
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .

          docker push --all-tags $IMG